window.DU2BAO2_CATEGORIES = [
  "Luxury Bags",
  "Watches",
  "Fashion",
  "Technology",
  "Jewelry",
  "Accessories",
  "Miscellaneous"
];

window.DU2BAO2_DEMO_PRODUCTS = [
  {
    id: "demo-1",
    brand: "CHANEL",
    title: "Classic Flap Medium",
    category: "Luxury Bags",
    price: 26800,
    condition: "Excellent",
    location: "Petaling Jaya",
    description: "Black quilted lambskin with gold-tone hardware. Includes a dust bag and card. Buyers should confirm all details with the seller before completing the transaction.",
    badge: "Featured listing",
    status: "approved",
    visual: "CC",
    created_at: "2026-07-18T10:00:00Z",
    seller_name: "DU2BAO2 Select",
    seller_verified: false,
    images: ["assets/luxury-bag.svg"]
  },
  {
    id: "demo-2",
    brand: "ROLEX",
    title: "Datejust 36",
    category: "Watches",
    price: 34900,
    condition: "Very good",
    location: "Kuala Lumpur",
    description: "Stainless steel Datejust 36 with original box. Light signs of wear from use. Product information is supplied by the seller.",
    badge: "Recent listing",
    status: "approved",
    visual: "◷",
    created_at: "2026-07-17T11:30:00Z",
    seller_name: "Time Archive",
    seller_verified: false,
    images: ["assets/watch.svg"]
  },
  {
    id: "demo-3",
    brand: "SONY",
    title: "Alpha A7 IV Body",
    category: "Technology",
    price: 7299,
    condition: "Excellent",
    location: "Petaling Jaya",
    description: "Full-frame mirrorless camera body with battery, charger and box. Seller states that the camera is fully operational. Buyers should test important functions before purchase.",
    badge: "Camera listing",
    status: "approved",
    visual: "α7",
    created_at: "2026-07-16T09:15:00Z",
    seller_name: "Camera Circle MY",
    seller_verified: false,
    images: ["assets/camera.svg"]
  },
  {
    id: "demo-4",
    brand: "LOUIS VUITTON",
    title: "Capucines Mini",
    category: "Luxury Bags",
    price: 17900,
    condition: "Excellent",
    location: "Shah Alam",
    description: "Capucines Mini with a clean interior and minor signs of use. Contact the seller for additional photos and item history.",
    badge: "New listing",
    status: "approved",
    visual: "LV",
    created_at: "2026-07-15T15:40:00Z",
    seller_name: "Closet Circle",
    seller_verified: false,
    images: []
  },
  {
    id: "demo-5",
    brand: "APPLE",
    title: "MacBook Pro 14-inch M3 Pro",
    category: "Technology",
    price: 6799,
    condition: "Excellent",
    location: "Petaling Jaya",
    description: "Well-maintained MacBook Pro with charger and original box. Battery and device information should be confirmed directly with the seller.",
    badge: "Technology listing",
    status: "approved",
    visual: "⌘",
    created_at: "2026-07-14T12:10:00Z",
    seller_name: "Tech Vault MY",
    seller_verified: false,
    images: ["assets/laptop.svg"]
  },
  {
    id: "demo-6",
    brand: "DIOR",
    title: "Silk Twill Scarf",
    category: "Accessories",
    price: 1280,
    condition: "Like new",
    location: "Puchong",
    description: "Printed silk twill scarf stored carefully and worn only twice. Additional details are available from the seller.",
    badge: "Price update",
    status: "approved",
    visual: "D",
    created_at: "2026-07-13T10:00:00Z",
    seller_name: "Second Story",
    seller_verified: false,
    images: []
  },
  {
    id: "demo-7",
    brand: "GUCCI",
    title: "GG Wool Blazer",
    category: "Fashion",
    price: 3200,
    condition: "Excellent",
    location: "Kuala Lumpur",
    description: "Structured GG wool blazer with a clean lining and no visible stains stated by the seller.",
    badge: "Fashion listing",
    status: "approved",
    visual: "GG",
    created_at: "2026-07-12T08:45:00Z",
    seller_name: "Edit Wardrobe",
    seller_verified: false,
    images: []
  },
  {
    id: "demo-8",
    brand: "ROYAL SELANGOR",
    title: "Limited Collectible Figure",
    category: "Miscellaneous",
    price: 4100,
    condition: "Like new",
    location: "Kepong",
    description: "Limited collectible display piece with original packaging and certificate stated by the seller.",
    badge: "Selected item",
    status: "approved",
    visual: "✦",
    created_at: "2026-07-11T13:20:00Z",
    seller_name: "Collector's Room",
    seller_verified: false,
    images: []
  }
];
