-- DU2BAO2 Supabase setup
-- Run this entire file once in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'DU2BAO2 Seller',
  whatsapp text not null default '',
  is_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 100),
  brand text not null check (char_length(brand) between 1 and 60),
  category text not null check (category in (
    'Luxury Bags', 'Watches', 'Fashion', 'Technology',
    'Jewelry', 'Accessories', 'Miscellaneous'
  )),
  price numeric(12,2) not null check (price > 0),
  condition text not null check (condition in ('Like new', 'Excellent', 'Very good', 'Good', 'Fair')),
  location text not null check (char_length(location) between 2 and 80),
  description text not null check (char_length(description) between 5 and 2000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'sold')),
  badge text not null default 'Admin reviewed',
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_images (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create index if not exists listings_status_created_idx on public.listings(status, created_at desc);
create index if not exists listings_category_idx on public.listings(category);
create index if not exists listings_seller_idx on public.listings(seller_id);
create index if not exists listing_images_listing_idx on public.listing_images(listing_id, sort_order);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admins where user_id = auth.uid());
$$;

alter table public.profiles enable row level security;
alter table public.admins enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.favorites enable row level security;

-- Profiles
DROP POLICY IF EXISTS "Profiles are publicly readable" ON public.profiles;
create policy "Profiles are publicly readable"
on public.profiles for select
using (true);

DROP POLICY IF EXISTS "Users create their own profile" ON public.profiles;
create policy "Users create their own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

DROP POLICY IF EXISTS "Users update their own profile" ON public.profiles;
create policy "Users update their own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Admin table: users can only detect their own membership. Service role can manage all rows.
DROP POLICY IF EXISTS "Users can read own admin membership" ON public.admins;
create policy "Users can read own admin membership"
on public.admins for select
to authenticated
using (user_id = auth.uid());

-- Listings
DROP POLICY IF EXISTS "Public reads approved listings" ON public.listings;
create policy "Public reads approved listings"
on public.listings for select
using (status = 'approved' or seller_id = auth.uid() or public.is_admin());

DROP POLICY IF EXISTS "Authenticated users create pending listings" ON public.listings;
create policy "Authenticated users create pending listings"
on public.listings for insert
to authenticated
with check (seller_id = auth.uid() and status = 'pending');

DROP POLICY IF EXISTS "Sellers update own non-approved state" ON public.listings;
create policy "Sellers update own non-approved state"
on public.listings for update
to authenticated
using (seller_id = auth.uid())
with check (seller_id = auth.uid() and status in ('pending', 'sold'));

DROP POLICY IF EXISTS "Admins update any listing" ON public.listings;
create policy "Admins update any listing"
on public.listings for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

DROP POLICY IF EXISTS "Sellers delete own pending listings" ON public.listings;
create policy "Sellers delete own pending listings"
on public.listings for delete
to authenticated
using (seller_id = auth.uid() and status = 'pending');

-- Listing images
DROP POLICY IF EXISTS "Images follow listing visibility" ON public.listing_images;
create policy "Images follow listing visibility"
on public.listing_images for select
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and (listings.status = 'approved' or listings.seller_id = auth.uid() or public.is_admin())
  )
);

DROP POLICY IF EXISTS "Sellers add images to own listings" ON public.listing_images;
create policy "Sellers add images to own listings"
on public.listing_images for insert
to authenticated
with check (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Sellers delete images from own listings" ON public.listing_images;
create policy "Sellers delete images from own listings"
on public.listing_images for delete
to authenticated
using (
  exists (
    select 1 from public.listings
    where listings.id = listing_images.listing_id
      and listings.seller_id = auth.uid()
  )
);

-- Favorites (database-ready; the current front-end also keeps a browser-local wishlist)
DROP POLICY IF EXISTS "Users read own favorites" ON public.favorites;
create policy "Users read own favorites"
on public.favorites for select
to authenticated
using (user_id = auth.uid());

DROP POLICY IF EXISTS "Users add own favorites" ON public.favorites;
create policy "Users add own favorites"
on public.favorites for insert
to authenticated
with check (user_id = auth.uid());

DROP POLICY IF EXISTS "Users remove own favorites" ON public.favorites;
create policy "Users remove own favorites"
on public.favorites for delete
to authenticated
using (user_id = auth.uid());

-- Public image bucket
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'listing-images',
  'listing-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

DROP POLICY IF EXISTS "Public can view listing images" ON storage.objects;
create policy "Public can view listing images"
on storage.objects for select
using (bucket_id = 'listing-images');

DROP POLICY IF EXISTS "Users upload into own image folder" ON storage.objects;
create policy "Users upload into own image folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'listing-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users delete own uploaded images" ON storage.objects;
create policy "Users delete own uploaded images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'listing-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- AFTER creating your own account, make it an admin with this command.
-- Replace the email before running it:
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'your-admin-email@example.com'
-- on conflict (user_id) do nothing;
